services:
  - type: web
    name: artibir-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: artibir-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.6

databases:
  - name: artibir-db
    databaseName: artibir
    user: artibir_user
    plan: free
